pipeline {
  agent { 
    docker { 
	image 'poisdeux/kore'
	args '-u root:root --privileged'
    }    
  }
  stages {
    stage('build') {
        steps {
            sh '''
                ./gradlew clean assembleFullRelease
            '''
        }
    }
    stage('run lint checks') {
      steps {
            sh '''
               #./gradlew lintFullRelease
            '''
      }
    }
    stage('run local tests') {
      steps {
            sh '''
               #./gradlew testFullDebugUnitTest
            '''
      }
    }
    stage('run device tests') {
      steps {
           timeout(time: 3, unit: 'MINUTES') {
            sh '''
                avdmanager -v create avd -f -g google_apis -b x86 -d 'Nexus 5' -n test -c 100M -k 'system-images;android-26;google_apis;x86'
                cp tools/jenkins/config.ini $HOME/.android/avd/test.avd/
            '''
            }
           timeout(time: 10, unit: 'MINUTES') {
            sh '''
                ./tools/jenkins/manage_emulator.sh -d test
            '''
           }
           sh '''
                # restart adb just to be sure it is available
                adb kill-server
                adb start-server
           '''
           sh '''
                ./gradlew connectedInstrumentationTestDebugAndroidTest
           '''
           timeout(time: 10, unit: 'MINUTES') {
               sh '''./tools/jenkins/manage_emulator.sh -p test'''
           }
      }
    }
  }
  post {
    always {
        junit './app/build/outputs/androidTest-results/**/*.xml'
        androidLint canComputeNew: false, defaultEncoding: '', healthy: '', pattern: './app/build/reports/lint-results*.xml', unHealthy: ''
    }
  }
}
